CREATE TABLE COMPANY(
    ID          SERIAL          PRIMARY KEY,
    NAME        VARCHAR(30)     NOT NULL,
    AGE         INTEGER         NOT NULL
);

INSERT INTO COMPANY (NAME, AGE)
VALUES ('Paul', 32);

INSERT INTO COMPANY (NAME, AGE)
VALUES ('Allen', 25);

INSERT INTO COMPANY (NAME, AGE)
VALUES ('Teddy', 23);

INSERT INTO COMPANY (NAME, AGE)
VALUES ('Mark', 25);

INSERT INTO COMPANY (NAME, AGE)
VALUES ('David', 27);

INSERT INTO COMPANY (NAME, AGE)
VALUES ('Kim', 29);

INSERT INTO COMPANY (NAME, AGE)
VALUES ('Tom', 24);

INSERT INTO COMPANY (NAME, AGE)
VALUES ('Jack', 27);

INSERT INTO COMPANY (NAME, AGE)
VALUES ('Lily', 22);

INSERT INTO COMPANY (NAME, AGE)
VALUES ('Sam', 24);

INSERT INTO COMPANY (NAME, AGE)
VALUES ('Charlie', 25);

INSERT INTO COMPANY (NAME, AGE)
VALUES ('Charlotte', 22);
